import type { Product } from "./types/product";

const SHOPS = [
  { name: "ArtisanPrints", slug: "artisanprints", avatar: "https://i.pravatar.cc/64?img=12" },
  { name: "WildInk Studio", slug: "wildink", avatar: "https://i.pravatar.cc/64?img=32" },
  { name: "Northwood Goods", slug: "northwood", avatar: "https://i.pravatar.cc/64?img=47" },
  { name: "Solstice Co.", slug: "solstice", avatar: "https://i.pravatar.cc/64?img=15" },
  { name: "Petal & Press", slug: "petalpress", avatar: "https://i.pravatar.cc/64?img=23" },
];

const img = (id: string, w = 800) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=${w}&q=80`;

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "p-001",
    slug: "vintage-sunset-mountains-tee",
    title: "Vintage Sunset Mountains Tee",
    price_cents: 2899,
    compare_price: 3899,
    images: [img("1521572163474-6864f9cf17ab")],
    category: "T-Shirts",
    tags: ["nature", "vintage", "outdoors"],
    shop: SHOPS[0],
    rating_avg: 4.8,
    rating_count: 247,
    sales_count: 1240,
    in_stock: true,
    is_featured: true,
    is_trending: true,
    free_shipping: true,
    badges: ["bestseller", "sale"],
  },
  {
    id: "p-002",
    slug: "minimalist-cat-portrait-mug",
    title: "Minimalist Cat Portrait Ceramic Mug",
    price_cents: 1799,
    images: [img("1514228742587-6b1558fcca3d")],
    category: "Mugs",
    tags: ["animals", "minimalist", "gift"],
    shop: SHOPS[1],
    rating_avg: 4.9,
    rating_count: 512,
    sales_count: 2100,
    in_stock: true,
    is_featured: true,
    is_trending: true,
    free_shipping: true,
    badges: ["bestseller"],
  },
  {
    id: "p-003",
    slug: "abstract-wave-poster",
    title: "Abstract Wave Giclée Art Poster",
    price_cents: 2499,
    images: [img("1513519245088-0e12902e5a38")],
    category: "Posters",
    tags: ["abstract", "art", "wall-decor"],
    shop: SHOPS[2],
    rating_avg: 4.7,
    rating_count: 89,
    sales_count: 320,
    in_stock: true,
    is_featured: false,
    is_trending: true,
    free_shipping: false,
    badges: ["new"],
  },
  {
    id: "p-004",
    slug: "cozy-forest-hoodie",
    title: "Cozy Forest Adventures Hoodie",
    price_cents: 4499,
    compare_price: 5499,
    images: [img("1556821840-3a63f95609a7")],
    category: "Hoodies",
    tags: ["nature", "cozy", "outdoors"],
    shop: SHOPS[3],
    rating_avg: 4.6,
    rating_count: 178,
    sales_count: 640,
    in_stock: true,
    is_featured: true,
    is_trending: false,
    free_shipping: true,
    badges: ["sale"],
  },
  {
    id: "p-005",
    slug: "wildflower-tote-bag",
    title: "Hand-Drawn Wildflower Canvas Tote",
    price_cents: 1999,
    images: [img("1544816155-12df9643f363")],
    category: "Tote Bags",
    tags: ["floral", "eco", "everyday"],
    shop: SHOPS[4],
    rating_avg: 4.9,
    rating_count: 304,
    sales_count: 980,
    in_stock: true,
    is_featured: false,
    is_trending: true,
    free_shipping: true,
    badges: ["eco"],
  },
  {
    id: "p-006",
    slug: "retro-arcade-phone-case",
    title: "Retro Arcade 80s Phone Case",
    price_cents: 2299,
    images: [img("1556656793-08538906a9f8")],
    category: "Phone Cases",
    tags: ["retro", "gaming", "funny"],
    shop: SHOPS[1],
    rating_avg: 4.5,
    rating_count: 142,
    sales_count: 410,
    in_stock: true,
    is_featured: false,
    is_trending: false,
    free_shipping: false,
    badges: ["new"],
  },
  {
    id: "p-007",
    slug: "celestial-moon-tee",
    title: "Celestial Moon Phases Pocket Tee",
    price_cents: 2699,
    images: [img("1503341504253-dff4815485f1")],
    category: "T-Shirts",
    tags: ["celestial", "minimalist", "night"],
    shop: SHOPS[0],
    rating_avg: 4.7,
    rating_count: 421,
    sales_count: 1500,
    in_stock: true,
    is_featured: true,
    is_trending: true,
    free_shipping: true,
    badges: ["bestseller"],
  },
  {
    id: "p-008",
    slug: "botanical-line-art-poster",
    title: "Botanical Line Art Print Set",
    price_cents: 3299,
    compare_price: 4299,
    images: [img("1490750967868-88aa4486c946")],
    category: "Posters",
    tags: ["botanical", "minimalist", "wall-decor"],
    shop: SHOPS[4],
    rating_avg: 4.8,
    rating_count: 263,
    sales_count: 870,
    in_stock: true,
    is_featured: true,
    is_trending: false,
    free_shipping: true,
    badges: ["sale", "madeToOrder"],
  },
  {
    id: "p-009",
    slug: "good-vibes-only-mug",
    title: "Good Vibes Only Stoneware Mug",
    price_cents: 1599,
    images: [img("1577937927133-66ef06acdf18")],
    category: "Mugs",
    tags: ["typography", "cheerful", "gift"],
    shop: SHOPS[2],
    rating_avg: 4.4,
    rating_count: 96,
    sales_count: 230,
    in_stock: true,
    is_featured: false,
    is_trending: false,
    free_shipping: false,
    badges: [],
  },
  {
    id: "p-010",
    slug: "mountain-explorer-hoodie",
    title: "Mountain Explorer Heavyweight Hoodie",
    price_cents: 4899,
    images: [img("1620799140408-edc6dcb6d633")],
    category: "Hoodies",
    tags: ["outdoors", "warm", "vintage"],
    shop: SHOPS[3],
    rating_avg: 4.9,
    rating_count: 387,
    sales_count: 1120,
    in_stock: true,
    is_featured: true,
    is_trending: true,
    free_shipping: true,
    badges: ["bestseller"],
  },
  {
    id: "p-011",
    slug: "sticker-pack-vibes",
    title: "Indie Vibes Sticker Pack (12 pcs)",
    price_cents: 1499,
    images: [img("1563089145-599997674d42")],
    category: "Stickers",
    tags: ["funny", "pack", "laptop"],
    shop: SHOPS[1],
    rating_avg: 4.6,
    rating_count: 215,
    sales_count: 690,
    in_stock: true,
    is_featured: false,
    is_trending: true,
    free_shipping: true,
    badges: ["new"],
  },
  {
    id: "p-012",
    slug: "dad-cap-embroidered",
    title: "Embroidered Logo Dad Cap",
    price_cents: 2499,
    compare_price: 2999,
    images: [img("1521369909029-2afed882baee")],
    category: "Hats",
    tags: ["streetwear", "minimal", "everyday"],
    shop: SHOPS[0],
    rating_avg: 4.5,
    rating_count: 134,
    sales_count: 410,
    in_stock: true,
    is_featured: false,
    is_trending: false,
    free_shipping: true,
    badges: ["sale"],
  },
  {
    id: "p-013",
    slug: "ocean-wave-tee",
    title: "Ocean Wave Watercolor Tee",
    price_cents: 2799,
    images: [img("1554568218-0f1715e72254")],
    category: "T-Shirts",
    tags: ["ocean", "watercolor", "summer"],
    shop: SHOPS[3],
    rating_avg: 4.7,
    rating_count: 198,
    sales_count: 580,
    in_stock: true,
    is_featured: true,
    is_trending: false,
    free_shipping: true,
    badges: [],
  },
  {
    id: "p-014",
    slug: "pet-portrait-poster",
    title: "Custom Pet Portrait Art Print",
    price_cents: 3899,
    images: [img("1543466835-00a7907e9de1")],
    category: "Posters",
    tags: ["custom", "pet", "gift"],
    shop: SHOPS[4],
    rating_avg: 5.0,
    rating_count: 612,
    sales_count: 1980,
    in_stock: true,
    is_featured: true,
    is_trending: true,
    free_shipping: false,
    badges: ["bestseller", "madeToOrder"],
  },
  {
    id: "p-015",
    slug: "geo-pattern-mug",
    title: "Geometric Pattern Espresso Mug",
    price_cents: 1899,
    images: [img("1572119865084-43c285814d63")],
    category: "Mugs",
    tags: ["geometric", "espresso", "modern"],
    shop: SHOPS[2],
    rating_avg: 4.6,
    rating_count: 121,
    sales_count: 340,
    in_stock: true,
    is_featured: false,
    is_trending: false,
    free_shipping: false,
    badges: [],
  },
  {
    id: "p-016",
    slug: "marble-phone-case",
    title: "Rose Marble Phone Case",
    price_cents: 2199,
    images: [img("1601784551446-20c9e07cdbdb")],
    category: "Phone Cases",
    tags: ["marble", "elegant", "feminine"],
    shop: SHOPS[4],
    rating_avg: 4.5,
    rating_count: 87,
    sales_count: 220,
    in_stock: true,
    is_featured: false,
    is_trending: false,
    free_shipping: true,
    badges: [],
  },
  {
    id: "p-017",
    slug: "skate-club-tee",
    title: "Underground Skate Club Tee",
    price_cents: 3199,
    images: [img("1583743814966-8936f5b7be1a")],
    category: "T-Shirts",
    tags: ["streetwear", "skate", "graphic"],
    shop: SHOPS[1],
    rating_avg: 4.8,
    rating_count: 356,
    sales_count: 980,
    in_stock: true,
    is_featured: true,
    is_trending: true,
    free_shipping: true,
    badges: ["bestseller"],
  },
  {
    id: "p-018",
    slug: "linen-tote-market",
    title: "Linen Market Tote Bag",
    price_cents: 2399,
    images: [img("1591561954557-26941169b49e")],
    category: "Tote Bags",
    tags: ["linen", "everyday", "eco"],
    shop: SHOPS[2],
    rating_avg: 4.7,
    rating_count: 142,
    sales_count: 380,
    in_stock: true,
    is_featured: false,
    is_trending: false,
    free_shipping: true,
    badges: ["eco"],
  },
  {
    id: "p-019",
    slug: "bookworm-sticker",
    title: "Bookworm Vinyl Sticker",
    price_cents: 499,
    images: [img("1532012197267-da84d127e765")],
    category: "Stickers",
    tags: ["books", "cute", "single"],
    shop: SHOPS[4],
    rating_avg: 4.9,
    rating_count: 89,
    sales_count: 410,
    in_stock: true,
    is_featured: false,
    is_trending: false,
    free_shipping: false,
    badges: ["new"],
  },
  {
    id: "p-020",
    slug: "denim-bucket-hat",
    title: "Washed Denim Bucket Hat",
    price_cents: 2899,
    compare_price: 3499,
    images: [img("1556306535-0f09a537f0a3")],
    category: "Hats",
    tags: ["denim", "summer", "y2k"],
    shop: SHOPS[3],
    rating_avg: 4.6,
    rating_count: 167,
    sales_count: 520,
    in_stock: true,
    is_featured: true,
    is_trending: true,
    free_shipping: true,
    badges: ["sale"],
  },
];
